branches:
  except:
    - gh-pages

before_build:
  nuget restore MrAdvice.sln

configuration: Release
platform: Any CPU

build:
  parallel: true   
  project: MrAdvice.sln
  publish_nuget: true
#  publish_nuget_symbols: true
  verbosity: minimal

artifacts:
  - path: '*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: rEYnR9JThbc6x8DdCo1K8+fgsGKzjNKzTZsldXFLYMm/tFPC7JWWvuKpVTrDBd+g
  skip_symbols: false

after_test:
  ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
