# Mr. Advice appveyor.yml script

version: '{branch}-{build}'

branches:
  only:
    - master
    - fody

before_build:
  nuget restore MrAdvice.sln

configuration: Release
platform: Any CPU

build:
  parallel: true   
  project: MrAdvice.sln
  publish_nuget: false
  publish_nuget_symbols: false
  verbosity: minimal

test:
  assemblies:
    - '**\*Test.exe'
    - '**\*Test.dll'

artifacts:
  - path: 'MrAdvice.Fody\bin\$(configuration)\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: rEYnR9JThbc6x8DdCo1K8+fgsGKzjNKzTZsldXFLYMm/tFPC7JWWvuKpVTrDBd+g
  skip_symbols: false

after_test:
  ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
